### ISSUE TITLE
 Some questions about program execution

### ISSUE THREAD

**Issue by HNU-YWB** [chaowentao/OccCasNet#1]
Hello, may I ask if this program can run on a Windows environment? I always encounter this error after setting up the environment on Windows, do you happen to know the reason for this error?

ImportError: SystemError: <built-in method __contains__ of dict object at 0x000002391EEDF120> returned a result with an error set

**Comment by HNU-YWB** [comment]
> 

![1689656421023](https://github.com/chaowentao/OccCasNet/assets/48237899/e624b031-d7cd-41bd-810c-a80de5565742)

**Comment by chaowentao** [comment]
@HNU-YWB Sorry, I don't try it on the Windows platform. It may be caused by the version of TensorFlow or Python. So I recommend you to use the Ubuntu platform and the given environment setting.

**Comment by HNU-YWB** [comment]
> @HNU-YWB Sorry, I don't try it on the Windows platform. It may be caused by the version of TensorFlow or Python. So I recommend you to use the Ubuntu platform and the given environment setting.

The previous issue has been resolved, which was caused by a numpy version compatibility problem. However, I have encountered a new problem and would like to ask for your help. According to the "read me" instructions, I downloaded the HCI Light field dataset from http://hci-lightfield.iwr.uni-heidelberg.de/. I unzipped the LF dataset and moved 'additional/, training/, test/, stratified/ ' into the 'hci_dataset/'. But in the program, the statement "boolmask_img4 = imageio.imread('hci_dataset/additional_invalid_area/kitchen/input_Cam040_invalid_ver2.png')" seems to not have found the corresponding folder and image.
![image](https://github.com/chaowentao/OccCasNet/assets/48237899/7eaa4bff-fc8b-4bf5-b0cd-366255442995)

**Comment by HNU-YWB** [comment]
> @HNU-YWB Sorry, I don't try it on the Windows platform. It may be caused by the version of TensorFlow or Python. So I recommend you to use the Ubuntu platform and the given environment setting.

Thank you for your help.

**Comment by chaowentao** [comment]
@HNU-YWB OK. If you have questions subsquently , pease keep contacting me.
